### ISSUE TITLE
problemの登録のはなし

### ISSUE THREAD

**Issue by ucpr** [SoyBeansLab/daizu-online-judge-old#3]
フォームから一つずつやるの辛いよねみたいな話になった気がするけど

```
❯ tree
.
├── description.md
├── input.md
├── output.md
├── samples
│   ├── sample1_in.md
│   ├── sample1_out.md
│   ├── sample2_in.md
│   └── sample2_out.md
└── testcases
    ├── input
    │   ├── 1.in
    │   ├── 2.in
    │   └── 3.in
    └── output
        ├── 1.out
        ├── 2.out
        └── 3.out

4 directories, 13 files
```

こんな感じのディレクトリを投げたら問題登録できるようにするかな〜みたいな話になった気がするけどあっちょりますか

**Comment by ucpr** [comment]
何か足りないのとかあったら教えて欲しさ〜〜〜

**Comment by ucpr** [comment]
@mosmosyrc 実行制限時間とかメモリ制限とかの情報ってどっから引っ張ってくるっていう話になったっけ？それともファイルとして置いとくんだった？

**Comment by mosmosyrc** [comment]
@ucpr 
確か、問題・入出力形式(？)・入出力例・入力例解説(任意)はファイルで、
その他はAPI叩いて持ってくる感じだった覚えがある！

**Comment by ucpr** [comment]
@nemusou  実行時間とかメモリのあれとかはjsonとかyamlとかの設定ファイル置いておくかな〜の気持ちですがいかがですか

**Comment by kurokoji** [comment]
これディレクトリ投げることでしか問題登録出来ない感じになるの?

**Comment by ucpr** [comment]
@kurokoji adminを実装するまではそうなるかも、admin実装したらフォームも作る気持ちでいる
ディレクトリを投げた場合はそのファイルをフォームに展開してくれるくらいにするかな〜という気持ち

**Comment by ucpr** [comment]
@kurokoji 問題登録、ディレクトリ投げるだけにして良い気がしてきたけどどうだろう
編集はadminのほうからフォームでできるようにはするけど

**Comment by kurokoji** [comment]
今後のことを考えるとどっちも実装すべきではあるように思う
